name: web3_dapp_browser
description: dapp browser.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
homepage: https://github.com/JamesBondMine/web3_dapp_browser

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
      sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  # 浏览器组件
  flutter_inappwebview: ^5.4.3+4
  # 分享
  share_plus: ^2.1.4


flutter:
  uses-material-design: true
  assets:
    - packages/web3_dapp_browser/assets/js/provider.min.js
